# Generated by Django 3.0.2 on 2020-01-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='flat_nr',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='adress',
            name='house_nr',
            field=models.IntegerField(blank=True),
        ),
    ]
