# Generated by Django 3.0.2 on 2020-01-25 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crawler', '0002_auto_20200125_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=128)),
                ('street', models.CharField(blank=True, max_length=256)),
                ('house_nr', models.IntegerField(blank=True)),
                ('flat_nr', models.IntegerField(blank=True)),
                ('phone_number', models.IntegerField(blank=True, default=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Adress',
        ),
    ]
