# Generated by Django 3.0.2 on 2020-01-27 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_auto_20200125_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
